Enhancement/move workspaces to other workspace group
iqb-berlin/studio-lite pull request #495
Opened 2023-09-08 08:39 UTC by jurei733

This pull request will display a move groups button in the wsg-admin workspaces panel. 
On click a window will be opened that gives information about your workspaces selection and a select field to select the destination workspace group. Afterwards the window will be closed and the workspaces list updated.

2023-09-11 08:44 UTC, mechtelm commented on apps/api/src/app/database/services/workspace.service.ts
> +  async patchMany(ids:string[], workspaceGroupId:number): Promise<void> {
Name der Funktion: Sollte doch klarstellen, dass die groupId geändert wird, oder?

2023-09-11 08:46 UTC, mechtelm commented on apps/api/src/app/admin/workspaces/workspaces.controller.ts
> +  @UseGuards(JwtAuthGuard, IsWorkspaceGroupAdminGuard)
Dieser Guard stellt nicht sicher, dass die Berechtigung für die Ziel-WorkspaceGroup besteht.

2023-09-11 08:47 UTC, mechtelm commented on apps/frontend/src/app/modules/shared/components/move-workspace/move-workspace.component.ts
> +  selector: 'studio-lite-move-workspace',
Wozu der selector? Die Komponente wird nur explizit aufgerufen.

2023-09-11 08:51 UTC, mechtelm commented on apps/frontend/src/app/modules/wsg-admin/components/workspace-menu/workspace-menu.component.ts
> +        if (selectedRows.length) {
Es muss die aktuelle WorkspaceGroup als Ziel herausgenommen werden. Danach muss es eine sinnvolle Meldung geben, wenn es keine weitere WorkspaceGroup als Ziel gibt, der user also nur auf eine Zugriff hat.

2023-09-11 08:58 UTC, mechtelm commented on apps/frontend/src/app/modules/wsg-admin/components/workspaces/workspaces.component.ts
> +  moveWorkspace(value: { selection: WorkspaceInListDto[], workspaceGroupId: number }) {
Das verstehe ich nicht. Diese Funktion wird doch durch das Event `workspaceMoved` ausgelöst, d. h. der Move ist schon passiert.

2023-09-11 15:45 UTC, jurei733 commented
Bitte prüfen ob die neuen Änderungen am Code den geforderten Anpassungen entsprechen.

2023-09-11 17:39 UTC, mechtelm requested changes
Quell-Workspacegroup-Rechte prüfen

2023-09-12 11:44 UTC, mechtelm approved these changes

2023-09-12 11:55 UTC, merged